name: 'streamfy'
description: 'Installs Streamfy CLI from source with required dependencies (e.g. Helm, Rust) and starts a Local Cluster. Used for developing streamfy.'
inputs:
  spus:  # number of SPUs
    description: 'number of SPUs to create for local cluster'
    required: false
    default: "1"
  cluster-type:
    description: 'Type of cluster (i.e. local or kubernetes)'
    required: true
    default: 'local'
  rust-log:
    description: "Add rust log options (e.g. debug, warn, info)"
    required: false
    default: 'warn'
  version:
    description: "Use a specific version of the streamfy CLI (e.g. latest, 0.6.0)"
    required: false
    # Blank default will use stable
    default: ''
  fvm_version:
    description: "Use a specific version of the fvm cli (e.g. latest, 0.18.1)"
runs:
  using: "composite"
  steps:
    - id: set-environment-variables
      run: |
        echo "SPU_NUMBER=${{ inputs.spus }}" >> $GITHUB_ENV
        echo "CLUSTER_TYPE=${{ inputs.cluster-type }}" >> $GITHUB_ENV
        echo "RUST_LOG=${{ inputs.rust-log }}" >> $GITHUB_ENV
        echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
        echo "STREAMFY_VERSION=${{ inputs.version }}" >> $GITHUB_ENV
        echo "FVM_VERSION=${{ inputs.fvm_version }}" >> $GITHUB_ENV
        echo "OS=${{ runner.os }}" >> $GITHUB_ENV
      shell: bash
    - id: install-streamfy
      run: ${{ github.action_path }}/actions/action-install-streamfy-cluster.sh
      shell: bash
    - id: set-streamfy-path
      shell: bash
      run: |
        echo "$HOME/.streamfy/bin" >> $GITHUB_PATH
