[package]
name = "sink-test-connector"
group = "streamfy"
version = "0.1.0"
apiVersion = "0.1.0"
streamfy = "0.10.0"
description = "Test Sink Connector"
license = "Apache-2.0"

[direction]
dest = true

[deployment]
binary = "sink-test-connector"
